<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Deterministic>true</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="data/alpha.bin" />
    <EmbeddedResource Include="data/beta.bin" />
  </ItemGroup>
</Project>
