name: Publish package to Maven Central, Github Packages

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  publish-jars:
    name: Publish JARs to GitHub
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Derive and validate version
        id: version
        shell: bash
        run: |
          raw_version="${GITHUB_REF#refs/tags/v}"
          if [[ ! "$raw_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: $raw_version. Must be v<major>.<minor>.<patch>." >&2
            exit 1
          fi
          echo "projectVersion=$raw_version" >> "$GITHUB_ENV"
          echo "version=$raw_version" >> "$GITHUB_OUTPUT"

      - name: Import PGP Key
        run: |
          echo "${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Publish JARs to GitHub Packages
        run:
          # src/cilantro has the build.sbt files, hence the cd to get there
          cd src/cilantro && SBT_OPTS="-Xmx8G -Duser.timezone=GMT" sbt "set ThisBuild / version := \"${{ env.projectVersion }}\"" +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_TARGET: github
          PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          # at present this value is not important as long as it isn't
          # "maven-central"
          PUBLISHING_DESTINATION: "github-packages"

      - name: Publish signed Jars to Maven Central
        # run a compound command:
        #  publishSigned should build the project to local staging and
        #    sign it
        #  sonaRelease should upload to to maven central and
        #    auto-release it
        run:
          cd src/cilantro && SBT_OPTS="-Xmx8G -Duser.timezone=GMT" sbt "set ThisBuild / version := \"${{ env.projectVersion }}\"" "+publishSigned ; sonaRelease"
        env:
          SONATYPE_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          # this will publish to maven central
          PUBLISHING_DESTINATION: "maven-central"
      - name: Index and upload ADG
        uses: spice-labs-inc/action-spice-labs-surveyor@v3
        with:
          spice_pass: "${{ secrets.SPICE_PASS }}"
          file_path: "${{ github.workspace }}"
          tag: "${{ github.event.repository.name }}"
